test:; RUST_BACKTRACE=1 cargo test --lib
schema:; cargo run --example schema
build:; cargo build --release --target wasm32-unknown-unknown
optimize:; cargo install cargo-run-script && cargo run-script optimize
.PHONY: schema
